### ISSUE TITLE
Get class loader of Java Context

### ISSUE THREAD

**Issue by jdiazgon** [m-m-m/code#22]
As a user of the m-m-m code library, I really would like to get the class loader of the Java context, so that I can easily use it in order to use reflection on that project.

I need this for the CobiGen CLI because we make use of reflection when generating Java code. If a user selects a Java entity, we need to build the class loader of that project.

Please find below the API that I used for getting the class loader:

```Java
JavaContext context = ParsingUtils.getJavaContext(inputFile, 
ParsingUtils.getProjectRoot(inputFile));

input = InputPreProcessor.process(cg, inputFile, context.getClassLoader());
```

**Comment by hohwille** [comment]
this one is extremely easy to do. As I have some minutes, I will do that now...

**Comment by hohwille** [comment]
I had implemented and fortunately comitted and pused the fix.
Now I wanted to do a new release and discovered that my entire sources, POMs, etc. and even the `.git` folder is gone locally. Only the empty folder structure is left. I assume Eclipse went berzerk and did this to me.

**Comment by hohwille** [comment]
https://repo1.maven.org/maven2/net/sf/m-m-m/mmm-code-java-impl/1.0.0-beta2/
